### ISSUE TITLE
There's no python syntax highlighting

### ISSUE THREAD

**Issue by PiyushHeHe** [Alex313031/atom-ng#2]
I'm on windows 11, if that helps.
As the title says there's no python syntax highlighting, also the ide-python package gives an error every time I restart.
also I don't know how to install packages on atom-ng.

The error says:

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.66.10 x64
**Electron**: 12.2.3
**OS**: Microsoft Windows 11 Pro
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.9.7

### Stack Trace

Failed to activate the ide-python package

```
At call.getFileName is not a function

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:279:25)
    at innerOk (assert.js:370:17)
    at ok (assert.js:390:3)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module.get_Module._compile (~/AppData/Local/atom-ng/app-1.66.10/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom-ng/app-1.66.10/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom-ng/app-1.66.10/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module.get_Module._compile (~/AppData/Local/atom-ng/app-1.66.10/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom-ng/app-1.66.10/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom-ng/app-1.66.10/resources/app/static/<embedded>:11:149229)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/ide-python/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module.get_Module._compile (~/AppData/Local/atom-ng/app-1.66.10/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom-ng/app-1.66.10/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
```

### Commands

```
```

### Non-Core Packages

```
atom-browser 2.1.4 
color-picker 2.3.2 
ide-python 1.9.7 
minimap 4.40.4 
yiff-view 0.1.4 
```

### Additional Information

![image](https://github.com/Alex313031/atom-ng/assets/134215620/dc503fb5-b2c4-426e-ab9b-802f0af599a7)

**Comment by Alex313031** [comment]
@PiyushHeHe Please see this comment about apm in atom-ng > https://github.com/Alex313031/atom-ng/issues/4#issuecomment-1599741451

What you can try is `apm-ng install atom-community/ide-python`

**Comment by fyndrkraze** [comment]
Hey, so I did the command, and it installed successfully, but I still get the same error, and syntax highlighting doesn't work
