### ISSUE TITLE
Failed to activate the atom-browser package

### ISSUE THREAD

**Issue by TrickBit** [Alex313031/atom-ng#7]
Action: Open Atom-ng ...

### Versions

**Atom**: 1.66.10 x64
**Electron**: 12.2.3
**OS**: Ubuntu 22.04.3
**Thrown From**: [atom-browser](ssh://git@github.com/Alex313031/atom-ng-browser) package 2.1.4

### Stack Trace

Failed to activate the atom-browser package

```
At Cannot find module 'express'
Require stack:
- /home/martin/.atom/packages/atom-ng-browser/lib/atom-browser-server.js
- /home/martin/.atom/packages/atom-ng-browser/lib/atom-browser.js
- /usr/share/atom-ng/resources/app.asar/static/index.html

Error: Cannot find module 'express'
Require stack:
- /home/martin/.atom/packages/atom-ng-browser/lib/atom-browser-server.js
- /home/martin/.atom/packages/atom-ng-browser/lib/atom-browser.js
- /usr/share/atom-ng/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at o._resolveFilename (electron/js2c/renderer_init.js:33:1118)
    at Function.get_Module._resolveFilename (/usr/share/atom-ng/resources/app/static/<embedded>:11:157942)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom-ng/resources/app/static/<embedded>:11:149229)
    at /packages/atom-ng-browser/lib/atom-browser-server.js:1:172)
    at /packages/atom-ng-browser/lib/atom-browser-server.js:27:3)
    at Module.get_Module._compile (/usr/share/atom-ng/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom-ng/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom-ng/resources/app/static/<embedded>:11:149229)
    at /packages/atom-ng-browser/lib/atom-browser.js:4:59)
    at /packages/atom-ng-browser/lib/atom-browser.js:279:2)
    at Module.get_Module._compile (/usr/share/atom-ng/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom-ng/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:88:18)
    at customRequire (/usr/share/atom-ng/resources/app/static/<embedded>:1:864704)
    at requireModule (/usr/share/atom-ng/resources/app/static/<embedded>:14:1223043)
    at Package.requireMainModule (/usr/share/atom-ng/resources/app/static/<embedded>:11:3360237)
    at Package.activateNow (/usr/share/atom-ng/resources/app/static/<embedded>:11:3348236)
    at /usr/share/atom-ng/resources/app/static/<embedded>:11:3348014
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-browser 2.1.4 
busy-signal 2.0.1 
color-picker 2.3.2 
intentions 2.1.1 
linter 3.4.0 
linter-shellcheck 1.6.0 
linter-ui-default 3.4.1 
minimap 4.40.4 
yiff-view 0.1.4 
```

### Additional Information

install node and npm
npm install express

go to start ...

Rinse and repeat

**Comment by TrickBit** [comment]
Moved this to the atom browser package page

**Comment by TrickBit** [comment]
re-opened  since one of my attempts to resolve  loops back to the editor itself.

Here Goes ...
 In Package Manager - 
uninstall atom-ng-browser

(thinking maybe an uninstall and re-install might bring in the editro module)

install atom-ng-browser
 here - we go ...


Installing “atom-ng-browser@2.1.4” failed.Hide output…
/usr/share/atom-ng/resources/app/apm/lib/install.js:256
          if (body.releases.latest) {
                            ^

TypeError: Cannot read property 'latest' of undefined
    at /usr/share/atom-ng/resources/app/apm/lib/install.js:256:29
    at Request._callback (/usr/share/atom-ng/resources/app/apm/lib/request.js:57:22)
    at Request.self.callback (/usr/share/atom-ng/resources/app/apm/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/usr/share/atom-ng/resources/app/apm/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/usr/share/atom-ng/resources/app/apm/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
