### ISSUE TITLE
Fetching featured packages failed

### ISSUE THREAD

**Issue by TrickBit** [Alex313031/atom-ng#8]
Versions
Atom: 1.66.10 x64
Electron: 12.2.3
OS: Ubuntu 22.04.3

Fetching featured packages failed ...

/usr/share/atom-ng/resources/app/apm/lib/featured.js:60
          packages = body.filter(function(pack) {
                          ^

TypeError: body.filter is not a function
    at /usr/share/atom-ng/resources/app/apm/lib/featured.js:60:27
    at Request._callback (/usr/share/atom-ng/resources/app/apm/lib/request.js:57:22)
    at Request.self.callback (/usr/share/atom-ng/resources/app/apm/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/usr/share/atom-ng/resources/app/apm/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/usr/share/atom-ng/resources/app/apm/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)

**Comment by Mishalabdullah** [comment]
![image](https://github.com/Alex313031/atom-ng/assets/85678545/d4f5cd0f-12d2-408c-83dd-39aff36275b0)

I am also facing the same issue..

**Comment by D4RKW1NT3R** [comment]
Looked it up and what I found is that body may not be an array, and so, has no function called filter. What I'm thinking is causing this is that the packages site is down on atom but I could be wrong, this is just from a  glance.
